x = input("Enter the input sequence: ");
h = input("Enter the impulse sequence: ");
y = conv(x, h);
figure; 
subplot(2,2,1);
stem(x);
xlabel("n");
ylabel("amplitude");
title("input sequence");
subplot(2,2,2);
stem(h);
xlabel("n");
ylabel("amplitude");
title("impulse sequence");
subplot(2,2,3);
stem(y);
xlabel("n");
ylabel("amplitude");
title("convoluted sequence");
disp("convoluted sequence");